version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - OPENAI_API_KEY=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
    depends_on:
      - neo4j
    volumes:
      - ./:/app  # Hot-reload

  neo4j:
    image: neo4j:5.17-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4jdata:/data

volumes:
  neo4jdata:
