version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - PORT=3000
    depends_on:
      - neo4j
    volumes:
      - ./src:/app/src  # Hot-reload for development

  neo4j:
    image: neo4j:5.17-community
    ports:
      - "7474:7474"  # HTTP interface (optional, for browser access)
      - "7687:7687"  # Bolt protocol (app connection)
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4jdata:/data

volumes:
  neo4jdata:
